# Generated by Django 5.0 on 2023-12-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_appellido', models.CharField(default='Desconocido', max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('mail', models.EmailField(default='no_email_contact@gmail.com', max_length=254)),
                ('edad', models.PositiveSmallIntegerField()),
                ('telefono', models.CharField(max_length=20)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('alta_paciente', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'consultorio_del_Dr',
            },
        ),
    ]
